// R734 bounded lifetime authority for forward acyclic multi-block native CIR.
// State: 16 qwords. Record: 16 qwords. Object identity, generation and CFG
// lifetime boundaries are derived from the sealed CIR, never from a consumer.
extern fn jj_cir_function_validate(p0:*i64,p1:i64)->i64;
extern fn jj_cir_function_node_block(p0:*i64,p1:i64,p2:i64)->i64;
extern fn jj_cir_function_block_reaches(p0:*i64,p1:i64,p2:i64,p3:i64)->i64;
extern fn jj_cir_function_block_dominates(p0:*i64,p1:i64,p2:i64,p3:i64)->i64;
extern fn jj_cir_function_node_dominates(p0:*i64,p1:i64,p2:i64,p3:i64)->i64;
extern fn jj_cir_function_backedge_count(p0:*i64,p1:i64)->i64;
extern fn jj_cir_object_kind(p0:i64)->i64;
extern fn jj_cir_object_flags(p0:i64)->i64;
extern fn jj_cir_object_storage(p0:i64)->i64;
extern fn jj_cir_object_word_valid(p0:i64)->i64;
extern fn jj_alias_location_bind(p0:*i64,p1:i64,p2:i64,p3:i64,p4:i64,p5:i64)->i64;
extern fn jj_alias_location_set_domain(p0:*i64,p1:i64,p2:i64,p3:i64)->i64;
extern fn jj_alias_location_valid(p0:*i64)->i64;
extern fn jj_alias_location_query(p0:*i64,p1:*i64)->i64;
fn jj_cir_lifetime_cycle_shape_valid(cir:*i64,cir_slots:i64)->i64{if cir==0{return 0;}var backedges:i64=jj_cir_function_backedge_count(cir,cir_slots);if backedges==0{return 1;}var node:i64=1;while node<=cir[3]{var nb:i64=cir[11]+(node-1)*4;var op:i64=cir[nb];if op==37{return 0;}if op==35{if jj_cir_function_node_block(cir,cir_slots,node)!=1{return 0;}}node=node+1;}return 1;}
fn jj_cir_lifetime_record_words()->i64{return 16;}
fn jj_cir_lifetime_ranges_disjoint(a:*i64,an:i64,b:*i64,bn:i64)->i64{
 if a==0{return 0;}if b==0{return 0;}if an<=0{return 0;}if bn<=0{return 0;}if an>0x0fffffffffffffff{return 0;}if bn>0x0fffffffffffffff{return 0;}var ab:i64=a as i64;var bb:i64=b as i64;var asz:i64=an*8;var bsz:i64=bn*8;if ab>0x7fffffffffffffff-asz{return 0;}if bb>0x7fffffffffffffff-bsz{return 0;}var ae:i64=ab+asz;var be:i64=bb+bsz;if ae<=bb{return 1;}if be<=ab{return 1;}return 0;
}
fn jj_cir_lifetime_zero(p:*i64,n:i64)->i64{if p==0{return 0;}if n<=0{return 0;}var i:i64=0;while i<n{p[i]=0;i=i+1;}return 1;}
fn jj_cir_lifetime_record_ptr(state:*i64,id:i64)->*i64{if state==0{return 0 as *i64;}if id<=0{return 0 as *i64;}if id>state[7]{return 0 as *i64;}return (state[4]+(id-1)*128) as *i64;}
fn jj_cir_lifetime_object_id(cir:*i64,kind:i64,storage:i64)->i64{if cir==0{return 0;}if kind<1{return 0;}if kind>4{return 0;}if storage<=0{return 0;}if storage>0x7fffffff{return 0;}return (storage<<3)|kind;}
fn jj_cir_lifetime_generation(cir:*i64,kind:i64,storage:i64,node:i64)->i64{if cir==0{return 0;}if kind<1{return 0;}if kind>4{return 0;}if storage<=0{return 0;}if node<=0{return 0;}if node>cir[3]{return 0;}return node;}
fn jj_cir_lifetime_scope(cir:*i64)->i64{if cir==0{return 0;}var scope:i64=cir as i64;if scope<=0{return 0;}return scope;}
fn jj_cir_lifetime_record_seal(r:*i64)->i64{if r==0{return 0;}var h:i64=(r as i64)^0x4a4a4c4946525331;var i:i64=0;while i<16{var v:i64=r[i];if i==15{v=0;}h=((h<<9)|(h>>>55))^v^((i+3)*0x45d9f3b);i=i+1;}if h==0{h=1;}return h;}
fn jj_cir_lifetime_record_valid(r:*i64,cir:*i64,cir_slots:i64)->i64{
 if r==0{return 0;}if cir==0{return 0;}if r[0]!=0x4a4a4c4946453031{return 0;}if r[1]!=2{return 0;}if r[2]<=0{return 0;}if r[3]<1{return 0;}if r[3]>4{return 0;}if r[4]<=0{return 0;}if r[5]<=0{return 0;}if r[5]>cir[3]{return 0;}if r[6]!=r[5]{return 0;}if r[7]<=r[6]{return 0;}if r[7]>cir[3]+1{return 0;}if r[8]<=0{return 0;}if r[8]>0x7fffffff{return 0;}if r[9]!=jj_cir_lifetime_object_id(cir,r[3],r[4]){return 0;}if r[10]!=jj_cir_lifetime_generation(cir,r[3],r[4],r[5]){return 0;}if r[11]<0{return 0;}if r[11]>31{return 0;}if r[12]!=jj_cir_function_node_block(cir,cir_slots,r[5]){return 0;}if r[12]<=0{return 0;}if r[13]!=jj_cir_lifetime_scope(cir){return 0;}if r[7]<=cir[3]{if r[14]!=jj_cir_function_node_block(cir,cir_slots,r[7]){return 0;}if r[14]<=0{return 0;}if jj_cir_function_node_dominates(cir,cir_slots,r[5],r[7])==0{return 0;}}else{if r[14]!=0{return 0;}}if r[3]==1{if r[11]!=24{return 0;}}if r[3]==2{if r[11]!=24{return 0;}}if r[3]==3{if r[11]!=2{return 0;}}if r[3]==4{if r[11]!=2{return 0;}}return r[15]==jj_cir_lifetime_record_seal(r);
}
fn jj_cir_lifetime_state_seal(state:*i64)->i64{
 if state==0{return 0;}var h:i64=(state as i64)^0x4a4a4c4946535431;var i:i64=0;while i<16{var v:i64=state[i];if i==11{v=0;}h=((h<<7)|(h>>>57))^v^((i+5)*0x9e3779b1);i=i+1;}var cir:*i64=state[2] as *i64;if cir!=0{h=h^cir[7];}i=1;while i<=state[7]{var r:*i64=(state[4]+(i-1)*128) as *i64;h=((h<<11)|(h>>>53))^r[15]^i;i=i+1;}if h==0{h=1;}return h;
}
fn jj_cir_lifetime_record_before(state:*i64,a:*i64,b:*i64)->i64{if state==0{return 0;}if a==0{return 0;}if b==0{return 0;}var cir:*i64=state[2] as *i64;if a[7]>cir[3]{return 0;}var slots:i64=state[3];if a[14]==b[12]{if a[7]<b[5]{return 1;}return 0;}return jj_cir_function_block_dominates(cir,slots,a[14],b[12]);}
fn jj_cir_lifetime_records_disjoint(state:*i64,a:*i64,b:*i64)->i64{if state==0{return 0;}if a==0{return 0;}if b==0{return 0;}var cir:*i64=state[2] as *i64;if cir==0{return 0;}if a[7]<=cir[3]{if jj_cir_lifetime_record_before(state,a,b)!=0{return 1;}}if b[7]<=cir[3]{if jj_cir_lifetime_record_before(state,b,a)!=0{return 1;}}return 0;}
fn jj_cir_lifetime_storage_overlap(state:*i64,candidate:*i64,limit:i64)->i64{
 if state==0{return 1;}if candidate==0{return 1;}var i:i64=1;while i<=limit{var r:*i64=jj_cir_lifetime_record_ptr(state,i);if r==0{return 1;}if r[4]==candidate[4]{if r[3]!=candidate[3]{return 1;}if jj_cir_lifetime_records_disjoint(state,r,candidate)==0{return 1;}}i=i+1;}return 0;
}
fn jj_cir_lifetime_find_end(cir:*i64,decl:i64,kind:i64)->i64{
 if cir==0{return 0;}var nodes:i64=cir[3];var found:i64=0;var node:i64=decl+1;while node<=nodes{var nb:i64=cir[11]+(node-1)*4;if cir[nb]==37{if cir[nb+2]==decl{if found!=0{return 0;}found=node;}}node=node+1;}if kind==3{if found!=0{return 0;}return nodes+1;}if kind==4{if found!=0{return 0;}return nodes+1;}if found==0{return nodes+1;}return found;
}
fn jj_cir_lifetime_parameter_bound(cir:*i64,decl:i64,storage:i64)->i64{
 if cir==0{return 0;}if cir[4]!=1{return 0;}if storage!=1{return 0;}if decl<=1{return 0;}var entry_end:i64=cir[12]+cir[13];if decl>=entry_end{return 0;}var found:i64=0;var node:i64=1;while node<decl{var nb:i64=cir[11]+(node-1)*4;if cir[nb]==1{if cir[nb+2]==0{found=found+1;}}node=node+1;}if found!=1{return 0;}return 1;
}
fn jj_cir_lifetime_state_valid(state:*i64)->i64{
 if state==0{return 0;}if ((state as i64)&7)!=0{return 0;}if state[0]!=0x4a4a4c4946533031{return 0;}if state[1]!=2{return 0;}if state[2]==0{return 0;}if (state[2]&7)!=0{return 0;}if state[3]<64{return 0;}if state[4]==0{return 0;}if (state[4]&7)!=0{return 0;}if state[5]<16{return 0;}if state[5]%16!=0{return 0;}if state[6]!=state[5]/16{return 0;}if state[6]>128{return 0;}if state[7]<0{return 0;}if state[7]>state[6]{return 0;}if state[8]<1{return 0;}if state[8]>64{return 0;}if state[9]!=1{return 0;}if state[10]!=2{return 0;}var z:i64=12;while z<16{if state[z]!=0{return 0;}z=z+1;}var cir:*i64=state[2] as *i64;if jj_cir_function_validate(cir,state[3])==0{return 0;}if jj_cir_lifetime_cycle_shape_valid(cir,state[3])==0{return 0;}if state[8]!=cir[2]{return 0;}if jj_cir_lifetime_ranges_disjoint(state,16,cir,state[3])==0{return 0;}if jj_cir_lifetime_ranges_disjoint(state,16,state[4] as *i64,state[5])==0{return 0;}if jj_cir_lifetime_ranges_disjoint(cir,state[3],state[4] as *i64,state[5])==0{return 0;}
 var i:i64=1;while i<=state[7]{var r:*i64=jj_cir_lifetime_record_ptr(state,i);if jj_cir_lifetime_record_valid(r,cir,state[3])==0{return 0;}if r[2]!=i{return 0;}var nb:i64=cir[11]+(r[5]-1)*4;if cir[nb]!=35{return 0;}if jj_cir_object_word_valid(cir[nb+2])==0{return 0;}if jj_cir_object_kind(cir[nb+2])!=r[3]{return 0;}if jj_cir_object_storage(cir[nb+2])!=r[4]{return 0;}if jj_cir_object_flags(cir[nb+2])!=r[11]{return 0;}if cir[nb+3]!=r[8]{return 0;}if r[7]!=jj_cir_lifetime_find_end(cir,r[5],r[3]){return 0;}if r[3]==3{if jj_cir_lifetime_parameter_bound(cir,r[5],r[4])==0{return 0;}}if jj_cir_lifetime_storage_overlap(state,r,i-1)!=0{return 0;}i=i+1;}
 var declarations:i64=0;var parameter_records:i64=0;var node:i64=1;while node<=cir[3]{var db:i64=cir[11]+(node-1)*4;if cir[db]==35{declarations=declarations+1;var matches:i64=0;var ri:i64=1;while ri<=state[7]{var dr:*i64=jj_cir_lifetime_record_ptr(state,ri);if dr[5]==node{matches=matches+1;if dr[3]==3{parameter_records=parameter_records+1;}}ri=ri+1;}if matches!=1{return 0;}}node=node+1;}if declarations!=state[7]{return 0;}if parameter_records>1{return 0;}if parameter_records==1{if cir[4]!=1{return 0;}}
 var tail:i64=state[7]*16;var rp:*i64=state[4] as *i64;while tail<state[5]{if rp[tail]!=0{return 0;}tail=tail+1;}return state[11]==jj_cir_lifetime_state_seal(state);
}
fn jj_cir_lifetime_abort(state:*i64,records:*i64,record_slots:i64)->i64{if state==0{return 0;}if records==0{return 0;}if record_slots<=0{return 0;}jj_cir_lifetime_zero(state,16);jj_cir_lifetime_zero(records,record_slots);return 1;}
fn jj_cir_lifetime_build(state:*i64,state_slots:i64,cir:*i64,cir_slots:i64,records:*i64,record_slots:i64)->i64{
 if state==0{return 0;}if state_slots!=16{return 0;}if cir==0{return 0;}if records==0{return 0;}if ((state as i64)&7)!=0{return 0;}if ((cir as i64)&7)!=0{return 0;}if ((records as i64)&7)!=0{return 0;}if record_slots<16{return 0;}if record_slots%16!=0{return 0;}if record_slots/16>128{return 0;}if jj_cir_function_validate(cir,cir_slots)==0{return 0;}if jj_cir_lifetime_cycle_shape_valid(cir,cir_slots)==0{return 0;}if jj_cir_lifetime_ranges_disjoint(state,state_slots,cir,cir_slots)==0{return 0;}if jj_cir_lifetime_ranges_disjoint(state,state_slots,records,record_slots)==0{return 0;}if jj_cir_lifetime_ranges_disjoint(cir,cir_slots,records,record_slots)==0{return 0;}jj_cir_lifetime_zero(state,16);jj_cir_lifetime_zero(records,record_slots);state[0]=0x4a4a4c4946533031;state[1]=2;state[2]=cir as i64;state[3]=cir_slots;state[4]=records as i64;state[5]=record_slots;state[6]=record_slots/16;state[7]=0;state[8]=cir[2];state[9]=1;state[10]=2;
 var node:i64=1;while node<=cir[3]{var nb:i64=cir[11]+(node-1)*4;if cir[nb]==35{if state[7]>=state[6]{jj_cir_lifetime_abort(state,records,record_slots);return 0;}var word:i64=cir[nb+2];if jj_cir_object_word_valid(word)==0{jj_cir_lifetime_abort(state,records,record_slots);return 0;}var id:i64=state[7]+1;var r:*i64=(state[4]+(id-1)*128) as *i64;r[0]=0x4a4a4c4946453031;r[1]=2;r[2]=id;r[3]=jj_cir_object_kind(word);r[4]=jj_cir_object_storage(word);r[5]=node;r[6]=node;r[7]=jj_cir_lifetime_find_end(cir,node,r[3]);r[8]=cir[nb+3];r[9]=jj_cir_lifetime_object_id(cir,r[3],r[4]);r[10]=jj_cir_lifetime_generation(cir,r[3],r[4],node);r[11]=jj_cir_object_flags(word);r[12]=jj_cir_function_node_block(cir,cir_slots,node);r[13]=jj_cir_lifetime_scope(cir);r[14]=0;if r[7]<=cir[3]{r[14]=jj_cir_function_node_block(cir,cir_slots,r[7]);}if r[12]<=0{jj_cir_lifetime_abort(state,records,record_slots);return 0;}if r[7]<=cir[3]{if r[14]<=0{jj_cir_lifetime_abort(state,records,record_slots);return 0;}if jj_cir_function_node_dominates(cir,cir_slots,node,r[7])==0{jj_cir_lifetime_abort(state,records,record_slots);return 0;}}if r[7]<=r[6]{jj_cir_lifetime_abort(state,records,record_slots);return 0;}if r[3]==3{if jj_cir_lifetime_parameter_bound(cir,r[5],r[4])==0{jj_cir_lifetime_abort(state,records,record_slots);return 0;}var prior_parameter:i64=1;while prior_parameter<id{var pr:*i64=jj_cir_lifetime_record_ptr(state,prior_parameter);if pr[3]==3{jj_cir_lifetime_abort(state,records,record_slots);return 0;}prior_parameter=prior_parameter+1;}}r[15]=jj_cir_lifetime_record_seal(r);state[7]=id;if jj_cir_lifetime_storage_overlap(state,r,id-1)!=0{jj_cir_lifetime_abort(state,records,record_slots);return 0;}}node=node+1;}
 node=1;while node<=cir[3]{var xb:i64=cir[11]+(node-1)*4;if cir[xb]==37{var target:i64=cir[xb+2];var matches:i64=0;var j:i64=1;while j<=state[7]{var rr:*i64=jj_cir_lifetime_record_ptr(state,j);if rr[5]==target{if rr[7]==node{matches=matches+1;}}j=j+1;}if matches!=1{jj_cir_lifetime_abort(state,records,record_slots);return 0;}}node=node+1;}state[11]=jj_cir_lifetime_state_seal(state);if jj_cir_lifetime_state_valid(state)==0{jj_cir_lifetime_abort(state,records,record_slots);return 0;}return 1;
}
fn jj_cir_lifetime_record_for_decl(state:*i64,node:i64)->i64{if jj_cir_lifetime_state_valid(state)==0{return 0;}var i:i64=1;while i<=state[7]{var r:*i64=jj_cir_lifetime_record_ptr(state,i);if r[5]==node{return i;}i=i+1;}return 0;}
fn jj_cir_lifetime_resolve(state:*i64,address_node:i64,at_node:i64,out:*i64)->i64{
 if jj_cir_lifetime_state_valid(state)==0{return 0;}if out==0{return 0;}var cir:*i64=state[2] as *i64;if jj_cir_lifetime_ranges_disjoint(out,4,state,16)==0{return 0;}if jj_cir_lifetime_ranges_disjoint(out,4,cir,state[3])==0{return 0;}if jj_cir_lifetime_ranges_disjoint(out,4,state[4] as *i64,state[5])==0{return 0;}if address_node<=0{return 0;}if at_node<=0{return 0;}if at_node>cir[3]{return 0;}if jj_cir_function_node_dominates(cir,state[3],address_node,at_node)==0{return 0;}var current:i64=address_node;var offset:i64=0;var steps:i64=0;while current>0{if jj_cir_function_node_dominates(cir,state[3],current,at_node)==0{return 0;}var nb:i64=cir[11]+(current-1)*4;var op:i64=cir[nb];if op==35{var id:i64=jj_cir_lifetime_record_for_decl(state,current);if id==0{return 0;}var r:*i64=jj_cir_lifetime_record_ptr(state,id);if jj_cir_function_node_dominates(cir,state[3],r[5],at_node)==0{return 0;}if r[7]<=cir[3]{var use_block:i64=jj_cir_function_node_block(cir,state[3],at_node);if use_block==r[14]{if at_node>=r[7]{return 0;}}else{if jj_cir_function_block_reaches(cir,state[3],r[14],use_block)!=0{return 0;}}}if offset<0{return 0;}if offset>r[8]{return 0;}out[0]=id;out[1]=offset;out[2]=r[8]-offset;out[3]=current;return 1;}if op!=36{return 0;}var delta:i64=cir[nb+3];if delta<0{return 0;}if offset>0x7fffffff-delta{return 0;}offset=offset+delta;current=cir[nb+2];steps=steps+1;if steps>cir[3]{return 0;}}return 0;
}
fn jj_cir_lifetime_location(state:*i64,address_node:i64,at_node:i64,access_size:i64,out:*i64)->i64{
 if jj_cir_lifetime_state_valid(state)==0{return 0;}if out==0{return 0;}var cir:*i64=state[2] as *i64;if jj_cir_lifetime_ranges_disjoint(out,12,state,16)==0{return 0;}if jj_cir_lifetime_ranges_disjoint(out,12,cir,state[3])==0{return 0;}if jj_cir_lifetime_ranges_disjoint(out,12,state[4] as *i64,state[5])==0{return 0;}if access_size<=0{return 0;}if access_size>0x7fffffff{return 0;}var d:[4]i64;if jj_cir_lifetime_resolve(state,address_node,at_node,d as *i64)==0{return 0;}if access_size>d[2]{return 0;}var r:*i64=jj_cir_lifetime_record_ptr(state,d[0]);if r==0{return 0;}jj_cir_lifetime_zero(out,12);if jj_alias_location_bind(out,r[3],r[9],d[1],access_size,r[11])==0{jj_cir_lifetime_zero(out,12);return 0;}if jj_alias_location_set_domain(out,0,r[13],r[10])==0{jj_cir_lifetime_zero(out,12);return 0;}if jj_alias_location_valid(out)==0{jj_cir_lifetime_zero(out,12);return 0;}return 1;
}
fn jj_cir_lifetime_find_location(state:*i64,location:*i64)->i64{
 if jj_cir_lifetime_state_valid(state)==0{return 0;}if jj_alias_location_valid(location)==0{return 0;}if location[2]==5{return 0;}var found:i64=0;var i:i64=1;while i<=state[7]{var r:*i64=jj_cir_lifetime_record_ptr(state,i);if r[3]==location[2]{if r[9]==location[3]{if r[10]==location[9]{if location[7]==0{if r[13]==location[8]{found=i;}}}}}i=i+1;}return found;
}
fn jj_cir_lifetime_proves_disjoint(state:*i64,a:*i64,b:*i64)->i64{
 if jj_cir_lifetime_state_valid(state)==0{return 0;}if jj_alias_location_valid(a)==0{return 0;}if jj_alias_location_valid(b)==0{return 0;}if a[2]==5{return 0;}if b[2]==5{return 0;}if a[2]!=b[2]{return 0;}if a[3]!=b[3]{return 0;}if a[7]!=b[7]{return 0;}if a[8]!=b[8]{return 0;}if a[9]==b[9]{return 0;}var ai:i64=jj_cir_lifetime_find_location(state,a);var bi:i64=jj_cir_lifetime_find_location(state,b);if ai==0{return 0;}if bi==0{return 0;}if ai==bi{return 0;}var ar:*i64=jj_cir_lifetime_record_ptr(state,ai);var br:*i64=jj_cir_lifetime_record_ptr(state,bi);return jj_cir_lifetime_records_disjoint(state,ar,br);
}
fn jj_alias_location_query_lifetime(state:*i64,a:*i64,b:*i64)->i64{var q:i64=jj_alias_location_query(a,b);if q==0{return 0;}if q!=2{return q;}if jj_cir_lifetime_proves_disjoint(state,a,b)!=0{return 1;}return 2;}
fn jj_cir_lifetime_access_record(state:*i64,id:i64)->*i64{if jj_cir_lifetime_state_valid(state)==0{return 0 as *i64;}return jj_cir_lifetime_record_ptr(state,id);}
fn jj_cir_lifetime_resource_contract(out:*i64,n:i64)->i64{if out==0{return 0;}if n<12{return 0;}out[0]=16;out[1]=16;out[2]=128;out[3]=2;out[4]=35;out[5]=36;out[6]=37;out[7]=4;out[8]=1;out[9]=1;out[10]=1;out[11]=2;return 1;}
fn jj_cir_lifetime_boundary_resource_contract(out:*i64,n:i64)->i64{if out==0{return 0;}if n<8{return 0;}out[0]=1;out[1]=1;out[2]=0;out[3]=64;out[4]=1;out[5]=0;out[6]=0;out[7]=0;return 1;}
