// R739 scalable graph authority for CIR functions.
// Storage and scratch are caller-provided. No graph semantic is encoded in a
// single machine word. The current CIR view still bounds blocks by its slots.
extern fn jj_cir_function_validate(p0:*i64,p1:i64)->i64;
extern fn jj_cir_function_block_capacity(p0:i64)->i64;
fn jj_gv2_ranges_disjoint(a:*i64,an:i64,b:*i64,bn:i64)->i64{if a==0{return 0;}if b==0{return 0;}if an<=0{return 0;}if bn<=0{return 0;}if an>0x0fffffffffffffff{return 0;}if bn>0x0fffffffffffffff{return 0;}var ab:i64=a as i64;var bb:i64=b as i64;if ab<0{return 0;}if bb<0{return 0;}var asz:i64=an*8;var bsz:i64=bn*8;if ab>0x7fffffffffffffff-asz{return 0;}if bb>0x7fffffffffffffff-bsz{return 0;}var ae:i64=ab+asz;var be:i64=bb+bsz;if ae<=bb{return 1;}if be<=ab{return 1;}return 0;}
fn jj_gv2_succ(cir:*i64,block:i64,index:i64)->i64{if cir==0{return 0;}if block<=0{return 0;}if block>cir[2]{return 0;}if index<0{return 0;}if index>1{return 0;}var bb:i64=12+(block-1)*6;var term:i64=cir[bb+2];if term==2{if index==0{return cir[bb+4]+1;}return 0;}if term==3{if index==0{return cir[bb+4]+1;}return cir[bb+5]+1;}return 0;}
fn jj_gv2_edge_count_raw(cir:*i64)->i64{if cir==0{return 0;}var edges:i64=0;var b:i64=1;while b<=cir[2]{if jj_gv2_succ(cir,b,0)>0{edges=edges+1;}if jj_gv2_succ(cir,b,1)>0{edges=edges+1;}b=b+1;}return edges;}
fn jj_gv2_required_raw(blocks:i64,edges:i64)->i64{if blocks<=0{return 0;}if edges<0{return 0;}if blocks>0x0fffffffffffffff/9{return 0;}var used:i64=16+blocks*9;if used>0x7fffffffffffffff-edges{return 0;}return used+edges;}
fn jj_gv2_work_required_raw(blocks:i64)->i64{if blocks<=0{return 0;}if blocks>0x0fffffffffffffff/7{return 0;}return blocks*7;}
fn jj_cir_graph_v2_required(cir:*i64,cir_slots:i64)->i64{if jj_cir_function_validate(cir,cir_slots)==0{return 0;}return jj_gv2_required_raw(cir[2],jj_gv2_edge_count_raw(cir));}
fn jj_cir_graph_v2_work_required(cir:*i64,cir_slots:i64)->i64{if jj_cir_function_validate(cir,cir_slots)==0{return 0;}return jj_gv2_work_required_raw(cir[2]);}
fn jj_gv2_record(g:*i64,block:i64)->i64{return 16+(block-1)*8;}
fn jj_gv2_pred_base(blocks:i64)->i64{return 16+blocks*8;}
fn jj_gv2_rpo_base(blocks:i64,edges:i64)->i64{return 16+blocks*8+edges;}
fn jj_gv2_edge_token(from:i64,to:i64)->i64{var x:i64=(from*0x45d9f3b)^((to*0x27d4eb2d)+0x4a4a4752);x=((x<<17)|(x>>>47))^(from+to*131);if x==0{x=1;}return x;}
fn jj_gv2_edge_digest_cir(cir:*i64)->i64{if cir==0{return 0;}var h:i64=0x4756324544474553;var from:i64=1;while from<=cir[2]{var si:i64=0;while si<2{var to:i64=jj_gv2_succ(cir,from,si);if to>0{var t:i64=jj_gv2_edge_token(from,to);h=h+t+((t<<23)|(t>>>41));}si=si+1;}from=from+1;}if h==0{h=1;}return h;}
fn jj_gv2_edge_digest_pred(g:*i64)->i64{if g==0{return 0;}var blocks:i64=g[4];var edges:i64=g[5];if blocks<=0{return 0;}if edges<0{return 0;}var pred_base:i64=jj_gv2_pred_base(blocks);var cursor:i64=0;var to:i64=1;var h:i64=0x4756324544474553;while to<=blocks{var rec:i64=jj_gv2_record(g,to);if g[rec+2]!=cursor{return 0;}var count:i64=g[rec+3];if count<0{return 0;}if count>edges-cursor{return 0;}var pi:i64=0;var previous:i64=0;while pi<count{var from:i64=g[pred_base+cursor+pi];if from<=0{return 0;}if from>blocks{return 0;}if from<=previous{return 0;}var t:i64=jj_gv2_edge_token(from,to);h=h+t+((t<<23)|(t>>>41));previous=from;pi=pi+1;}cursor=cursor+count;to=to+1;}if cursor!=edges{return 0;}if h==0{h=1;}return h;}
fn jj_gv2_zero(p:*i64,n:i64)->i64{if p==0{return 0;}if n<0{return 0;}var i:i64=0;while i<n{p[i]=0;i=i+1;}return 1;}
fn jj_gv2_seal(g:*i64)->i64{if g==0{return 0;}var used:i64=g[6];if used<16{return 0;}var h:i64=(g as i64)^0x4a4a475241503256;var i:i64=0;while i<used{var v:i64=g[i];if i==12{v=0;}h=((h<<7)|(h>>>57))^v^((i+11)*0x9e37);i=i+1;}if h==0{h=1;}return h;}
fn jj_gv2_idom_intersect(g:*i64,a0:i64,b0:i64,blocks:i64)->i64{var a:i64=a0;var b:i64=b0;var steps:i64=0;while a!=b{if a<=0{return 0;}if b<=0{return 0;}if a>blocks{return 0;}if b>blocks{return 0;}if steps>blocks*2{return 0;}var ar:i64=g[jj_gv2_record(g,a)+4];var br:i64=g[jj_gv2_record(g,b)+4];if ar<=0{return 0;}if br<=0{return 0;}if ar>br{a=g[jj_gv2_record(g,a)+5];}else{if br>ar{b=g[jj_gv2_record(g,b)+5];}else{return 0;}}steps=steps+1;}return a;}
fn jj_gv2_dominates_raw(g:*i64,dom:i64,use:i64)->i64{if g==0{return 0;}var blocks:i64=g[4];if dom<=0{return 0;}if use<=0{return 0;}if dom>blocks{return 0;}if use>blocks{return 0;}var cur:i64=use;var steps:i64=0;while cur>0{if cur==dom{return 1;}if cur==1{return 0;}cur=g[jj_gv2_record(g,cur)+5];steps=steps+1;if steps>blocks{return 0;}}return 0;}
fn jj_gv2_build_rpo(g:*i64,work:*i64,blocks:i64,edges:i64)->i64{var rpo_base:i64=jj_gv2_rpo_base(blocks,edges);var sp:i64=1;var finish_count:i64=0;work[0]=1;work[blocks]=1;work[blocks*2]=0;while sp>0{var top:i64=sp-1;var node:i64=work[blocks+top];var next:i64=work[blocks*2+top];if next<2{work[blocks*2+top]=next+1;var succ:i64=g[jj_gv2_record(g,node)+next];if succ>0{if work[succ-1]==0{work[succ-1]=1;work[blocks+sp]=succ;work[blocks*2+sp]=0;sp=sp+1;}}}else{work[blocks*3+finish_count]=node;finish_count=finish_count+1;sp=sp-1;}}if finish_count!=blocks{return 0;}var i:i64=0;while i<blocks{var out_node:i64=work[blocks*3+blocks-1-i];g[rpo_base+i]=out_node;g[jj_gv2_record(g,out_node)+4]=i+1;g[jj_gv2_record(g,out_node)+7]=1;i=i+1;}g[8]=blocks;return 1;}
fn jj_gv2_build_idom(g:*i64,blocks:i64,edges:i64)->i64{var pred_base:i64=jj_gv2_pred_base(blocks);var rpo_base:i64=jj_gv2_rpo_base(blocks,edges);g[jj_gv2_record(g,1)+5]=1;var changed:i64=1;var pass:i64=0;while changed!=0{if pass>blocks{return 0;}changed=0;var ri:i64=1;while ri<blocks{var block:i64=g[rpo_base+ri];var rec:i64=jj_gv2_record(g,block);var start:i64=g[rec+2];var count:i64=g[rec+3];var p:i64=0;var new_idom:i64=0;while p<count{var pred:i64=g[pred_base+start+p];if g[jj_gv2_record(g,pred)+5]!=0{if new_idom==0{new_idom=pred;}else{new_idom=jj_gv2_idom_intersect(g,pred,new_idom,blocks);if new_idom==0{return 0;}}}p=p+1;}if new_idom==0{return 0;}if g[rec+5]!=new_idom{g[rec+5]=new_idom;changed=1;}ri=ri+1;}pass=pass+1;}return 1;}
fn jj_gv2_build_scc(g:*i64,work:*i64,blocks:i64,edges:i64)->i64{var rpo_base:i64=jj_gv2_rpo_base(blocks,edges);var pred_base:i64=jj_gv2_pred_base(blocks);var i:i64=0;while i<blocks{work[i]=0;g[jj_gv2_record(g,i+1)+6]=0;i=i+1;}var scc:i64=0;i=0;while i<blocks{var root:i64=g[rpo_base+i];if work[root-1]==0{scc=scc+1;var sp:i64=1;work[blocks]=root;work[root-1]=1;while sp>0{sp=sp-1;var node:i64=work[blocks+sp];g[jj_gv2_record(g,node)+6]=scc;var rec:i64=jj_gv2_record(g,node);var start:i64=g[rec+2];var count:i64=g[rec+3];var p:i64=0;while p<count{var pred:i64=g[pred_base+start+p];if work[pred-1]==0{work[pred-1]=1;work[blocks+sp]=pred;sp=sp+1;}p=p+1;}}}i=i+1;}g[9]=scc;return 1;}
fn jj_gv2_prepare_scc_stats(g:*i64,work:*i64,blocks:i64)->i64{var size_base:i64=blocks*5;var entry_base:i64=blocks*6;var clear_index:i64=0;while clear_index<blocks{work[size_base+clear_index]=0;work[entry_base+clear_index]=0;clear_index=clear_index+1;}var count_block:i64=1;while count_block<=blocks{var count_sid:i64=g[jj_gv2_record(g,count_block)+6];if count_sid<=0{return 0;}work[size_base+count_sid-1]=work[size_base+count_sid-1]+1;count_block=count_block+1;}var entry_block:i64=1;while entry_block<=blocks{var entry_rec:i64=jj_gv2_record(g,entry_block);var entry_sid:i64=g[entry_rec+6];var has_external:i64=0;var pred_base:i64=jj_gv2_pred_base(blocks);var pred_index:i64=0;while pred_index<g[entry_rec+3]{var entry_pred:i64=g[pred_base+g[entry_rec+2]+pred_index];if g[jj_gv2_record(g,entry_pred)+6]!=entry_sid{has_external=1;}pred_index=pred_index+1;}if has_external!=0{work[entry_base+entry_sid-1]=work[entry_base+entry_sid-1]+1;}entry_block=entry_block+1;}return 1;}
fn jj_gv2_scc_cyclic(g:*i64,work:*i64,blocks:i64,sid:i64)->i64{var size_base:i64=blocks*5;if work[size_base+sid-1]>1{return 1;}var cycle_block:i64=1;while cycle_block<=blocks{var cycle_rec:i64=jj_gv2_record(g,cycle_block);if g[cycle_rec+6]==sid{if g[cycle_rec]==cycle_block{return 1;}if g[cycle_rec+1]==cycle_block{return 1;}}cycle_block=cycle_block+1;}return 0;}
fn jj_gv2_scc_header(g:*i64,work:*i64,blocks:i64,sid:i64)->i64{var entry_base:i64=blocks*6;var entries:i64=work[entry_base+sid-1];if entries==0{if g[jj_gv2_record(g,1)+6]==sid{return 1;}return 0;}if entries!=1{return 0;}var header_block:i64=1;var pred_base:i64=jj_gv2_pred_base(blocks);while header_block<=blocks{var header_rec:i64=jj_gv2_record(g,header_block);if g[header_rec+6]==sid{var pred_index:i64=0;while pred_index<g[header_rec+3]{var header_pred:i64=g[pred_base+g[header_rec+2]+pred_index];if g[jj_gv2_record(g,header_pred)+6]!=sid{return header_block;}pred_index=pred_index+1;}}header_block=header_block+1;}return 0;}
fn jj_gv2_scc_reducible(g:*i64,blocks:i64,sid:i64,header:i64)->i64{if header<=0{return 0;}var member_block:i64=1;while member_block<=blocks{if g[jj_gv2_record(g,member_block)+6]==sid{if jj_gv2_dominates_raw(g,header,member_block)==0{return 0;}}member_block=member_block+1;}return 1;}
fn jj_gv2_mark_scc(g:*i64,blocks:i64,sid:i64,header:i64,reducible:i64)->i64{var mark_block:i64=1;while mark_block<=blocks{var mark_rec:i64=jj_gv2_record(g,mark_block);if g[mark_rec+6]==sid{g[mark_rec+7]=g[mark_rec+7]|2;if reducible!=0{g[mark_rec+7]=g[mark_rec+7]|4;}else{g[mark_rec+7]=g[mark_rec+7]|8;}if mark_block==header{g[mark_rec+7]=g[mark_rec+7]|16;}}mark_block=mark_block+1;}return 1;}
fn jj_gv2_classify(g:*i64,work:*i64,blocks:i64)->i64{if jj_gv2_prepare_scc_stats(g,work,blocks)==0{return 0;}var reducible_count:i64=0;var irreducible_count:i64=0;var classify_sid:i64=1;while classify_sid<=g[9]{if jj_gv2_scc_cyclic(g,work,blocks,classify_sid)!=0{var classify_header:i64=jj_gv2_scc_header(g,work,blocks,classify_sid);var classify_reducible:i64=jj_gv2_scc_reducible(g,blocks,classify_sid,classify_header);if classify_reducible!=0{reducible_count=reducible_count+1;}else{irreducible_count=irreducible_count+1;}if jj_gv2_mark_scc(g,blocks,classify_sid,classify_header,classify_reducible)==0{return 0;}}classify_sid=classify_sid+1;}g[10]=reducible_count;g[11]=irreducible_count;return 1;}
fn jj_cir_graph_v2_build(g:*i64,g_slots:i64,work:*i64,work_slots:i64,cir:*i64,cir_slots:i64)->i64{if g==0{return 0;}if work==0{return 0;}if cir==0{return 0;}if ((g as i64)&7)!=0{return 0;}if ((work as i64)&7)!=0{return 0;}if ((cir as i64)&7)!=0{return 0;}if jj_cir_function_validate(cir,cir_slots)==0{return 0;}var blocks:i64=cir[2];var edges:i64=jj_gv2_edge_count_raw(cir);var used:i64=jj_gv2_required_raw(blocks,edges);var need_work:i64=jj_gv2_work_required_raw(blocks);if used<=0{return 0;}if need_work<=0{return 0;}if g_slots<used{return 0;}if work_slots<need_work{return 0;}if jj_gv2_ranges_disjoint(g,g_slots,work,work_slots)==0{return 0;}if jj_gv2_ranges_disjoint(g,g_slots,cir,cir_slots)==0{return 0;}if jj_gv2_ranges_disjoint(work,work_slots,cir,cir_slots)==0{return 0;}jj_gv2_zero(g,used);jj_gv2_zero(work,need_work);g[0]=0x4a4a475241503256;g[1]=2;g[2]=cir as i64;g[3]=cir_slots;g[4]=blocks;g[5]=edges;g[6]=used;g[7]=cir[7];g[13]=g as i64;g[14]=need_work;g[15]=jj_gv2_edge_digest_cir(cir);if g[15]==0{jj_gv2_zero(g,used);return 0;}var block:i64=1;while block<=blocks{var layout_rec:i64=jj_gv2_record(g,block);g[layout_rec]=jj_gv2_succ(cir,block,0);g[layout_rec+1]=jj_gv2_succ(cir,block,1);block=block+1;}var si:i64=0;block=1;while block<=blocks{si=0;while si<2{var count_target:i64=g[jj_gv2_record(g,block)+si];if count_target>0{g[jj_gv2_record(g,count_target)+3]=g[jj_gv2_record(g,count_target)+3]+1;}si=si+1;}block=block+1;}var cursor:i64=0;block=1;while block<=blocks{var prefix_rec:i64=jj_gv2_record(g,block);g[prefix_rec+2]=cursor;work[blocks*4+block-1]=cursor;cursor=cursor+g[prefix_rec+3];block=block+1;}if cursor!=edges{jj_gv2_zero(g,used);return 0;}var pred_base:i64=jj_gv2_pred_base(blocks);block=1;while block<=blocks{si=0;while si<2{var fill_target:i64=g[jj_gv2_record(g,block)+si];if fill_target>0{var fill_pos:i64=work[blocks*4+fill_target-1];g[pred_base+fill_pos]=block;work[blocks*4+fill_target-1]=fill_pos+1;}si=si+1;}block=block+1;}if jj_gv2_build_rpo(g,work,blocks,edges)==0{jj_gv2_zero(g,used);return 0;}if jj_gv2_build_idom(g,blocks,edges)==0{jj_gv2_zero(g,used);return 0;}if jj_gv2_build_scc(g,work,blocks,edges)==0{jj_gv2_zero(g,used);return 0;}if jj_gv2_classify(g,work,blocks)==0{jj_gv2_zero(g,used);return 0;}g[12]=jj_gv2_seal(g);if g[12]==0{jj_gv2_zero(g,used);return 0;}return 1;}
fn jj_cir_graph_v2_valid(g:*i64,g_slots:i64)->i64{if g==0{return 0;}if ((g as i64)&7)!=0{return 0;}if g[0]!=0x4a4a475241503256{return 0;}if g[1]!=2{return 0;}if g[2]==0{return 0;}if (g[2]&7)!=0{return 0;}if g[3]<64{return 0;}var cir:*i64=g[2] as *i64;if jj_cir_function_validate(cir,g[3])==0{return 0;}if cir[7]!=g[7]{return 0;}if g[4]<=0{return 0;}if g[5]<0{return 0;}if g[6]!=jj_gv2_required_raw(g[4],g[5]){return 0;}if g[6]>g_slots{return 0;}if g[8]!=g[4]{return 0;}if g[9]<=0{return 0;}if g[9]>g[4]{return 0;}if g[10]<0{return 0;}if g[11]<0{return 0;}if g[10]+g[11]>g[9]{return 0;}if g[13]!=(g as i64){return 0;}if g[14]!=jj_gv2_work_required_raw(g[4]){return 0;}if g[15]==0{return 0;}var check_block:i64=1;while check_block<=g[4]{var check_rec:i64=jj_gv2_record(g,check_block);if g[check_rec]!=jj_gv2_succ(cir,check_block,0){return 0;}if g[check_rec+1]!=jj_gv2_succ(cir,check_block,1){return 0;}check_block=check_block+1;}var cir_edge_digest:i64=jj_gv2_edge_digest_cir(cir);if cir_edge_digest==0{return 0;}if g[15]!=cir_edge_digest{return 0;}if jj_gv2_edge_digest_pred(g)!=cir_edge_digest{return 0;}if g[12]!=jj_gv2_seal(g){return 0;}return 1;}

fn jj_cir_graph_v2_verify(g:*i64,g_slots:i64,rival:*i64,rival_slots:i64,work:*i64,work_slots:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}if rival==0{return 0;}if work==0{return 0;}var cir:*i64=g[2] as *i64;var cir_slots:i64=g[3];if rival_slots<g[6]{return 0;}if work_slots<g[14]{return 0;}if jj_gv2_ranges_disjoint(g,g_slots,rival,rival_slots)==0{return 0;}if jj_gv2_ranges_disjoint(g,g_slots,work,work_slots)==0{return 0;}if jj_gv2_ranges_disjoint(rival,rival_slots,work,work_slots)==0{return 0;}if jj_gv2_ranges_disjoint(rival,rival_slots,cir,cir_slots)==0{return 0;}if jj_gv2_ranges_disjoint(work,work_slots,cir,cir_slots)==0{return 0;}if jj_cir_graph_v2_build(rival,rival_slots,work,work_slots,cir,cir_slots)==0{return 0;}var verify_index:i64=0;while verify_index<g[6]{if verify_index!=12{if verify_index!=13{if g[verify_index]!=rival[verify_index]{return 0;}}}verify_index=verify_index+1;}if jj_cir_graph_v2_valid(rival,rival_slots)==0{return 0;}return 1;}
fn jj_cir_graph_v2_block_count(g:*i64,g_slots:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}return g[4];}
fn jj_cir_graph_v2_edge_count(g:*i64,g_slots:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}return g[5];}
fn jj_cir_graph_v2_scc_count(g:*i64,g_slots:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}return g[9];}
fn jj_cir_graph_v2_reducible_cycle_count(g:*i64,g_slots:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}return g[10];}
fn jj_cir_graph_v2_irreducible_cycle_count(g:*i64,g_slots:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}return g[11];}
fn jj_cir_graph_v2_idom(g:*i64,g_slots:i64,block:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}if block<=0{return 0;}if block>g[4]{return 0;}return g[jj_gv2_record(g,block)+5];}
fn jj_cir_graph_v2_dominates(g:*i64,g_slots:i64,dom:i64,use:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}return jj_gv2_dominates_raw(g,dom,use);}
fn jj_cir_graph_v2_scc(g:*i64,g_slots:i64,block:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}if block<=0{return 0;}if block>g[4]{return 0;}return g[jj_gv2_record(g,block)+6];}
fn jj_cir_graph_v2_flags(g:*i64,g_slots:i64,block:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}if block<=0{return 0;}if block>g[4]{return 0;}return g[jj_gv2_record(g,block)+7];}
fn jj_cir_graph_v2_pred_count(g:*i64,g_slots:i64,block:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}if block<=0{return 0;}if block>g[4]{return 0;}return g[jj_gv2_record(g,block)+3];}
fn jj_cir_graph_v2_pred_at(g:*i64,g_slots:i64,block:i64,index:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}if block<=0{return 0;}if block>g[4]{return 0;}var rec:i64=jj_gv2_record(g,block);if index<0{return 0;}if index>=g[rec+3]{return 0;}var pred_base:i64=jj_gv2_pred_base(g[4]);return g[pred_base+g[rec+2]+index];}
fn jj_cir_graph_v2_rpo_at(g:*i64,g_slots:i64,index:i64)->i64{if jj_cir_graph_v2_valid(g,g_slots)==0{return 0;}if index<0{return 0;}if index>=g[4]{return 0;}return g[jj_gv2_rpo_base(g[4],g[5])+index];}
fn jj_cir_graph_v2_resource_contract(out:*i64,n:i64)->i64{if out==0{return 0;}if n<16{return 0;}out[0]=2;out[1]=8;out[2]=16;out[3]=7;out[4]=1;out[5]=1;out[6]=1;out[7]=1;out[8]=1;out[9]=1;out[10]=1;out[11]=65536;out[12]=jj_cir_function_block_capacity(65536);out[13]=0;out[14]=0;out[15]=0;return 1;}
